const test = require('ava');
const { exec } = require('../src/index');

test.skip('exec with valid definition', async t => {
  const definition = "{\r\n  \"metadata\": {\r\n    \"name\": \"workflow-name\"\r\n  },\r\n  \"input\": [\r\n    \"user\",\r\n    \"github_token\",\r\n    \"slack_token\",\r\n    \"slack_channel\",\r\n    \"slack_userid\"\r\n  ],\r\n  \"stages\": [\r\n    {\r\n      \"name\": \"get_repositories\",\r\n      \"steps\": [\r\n        {\r\n          \"name\": \"fetch_github\",\r\n          \"type\": \"http\",\r\n          \"method\": \"post\",\r\n          \"url\": \"https:\/\/api.github.com\/graphql\",\r\n          \"headers\": [\r\n            {\r\n              \"Authentication\": \"%{input.github_token}\"\r\n            }\r\n          ],\r\n          \"body\": {\r\n            \"query\": \"query($username: String!) { user(login: $username) { repositories(first: 10) { nodes { name } } } }\",\r\n            \"username\": \"%{input.user}\"\r\n          },\r\n          \"output\": {\r\n            \"repositories\": \"[.data.user.repositories.nodes[].name] | join(\\\", \\\")\"\r\n          }\r\n        }\r\n      ]\r\n    },\r\n    {\r\n      \"name\": \"publish_in_slack\",\r\n      \"steps\": [\r\n        {\r\n          \"name\": \"send_message_to_channel\",\r\n          \"type\": \"http\",\r\n          \"method\": \"post\",\r\n          \"url\": \"https:\/\/slack.com\/api\/chat.postMessage\",\r\n          \"body\": {\r\n            \"token\": \"%{input.slack_token}\",\r\n            \"channel\": \"%{input.slack_channel}\",\r\n            \"message\": \"User %{input.user} are: %{output.fetch_github.repositories}\"\r\n          }\r\n        },\r\n        {\r\n          \"name\": \"send_message_to_user\",\r\n          \"type\": \"http\",\r\n          \"method\": \"post\",\r\n          \"url\": \"https:\/\/slack.com\/api\/chat.postMessage\",\r\n          \"body\": {\r\n            \"token\": \"%{input.slack_token}\",\r\n            \"channel\": \"%{input.slack_userid}\",\r\n            \"message\": \"Your repos are: %{output.fetch_github.repositories}\"\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  ]\r\n}";

  const input = {};
  await exec(definition, input);
});

test('exec easier definition', async t => {
  const definition = "{\r\n  \"metadata\": {\r\n    \"name\": \"workflow-name\"\r\n  },\r\n  \"input\": [\r\n    \"value\"\r\n  ],\r\n  \"stages\": [\r\n    {\r\n      \"name\": \"get_users\",\r\n      \"steps\": [\r\n        {\r\n          \"name\": \"fetch_fake_api\",\r\n          \"type\": \"http\",\r\n          \"method\": \"get\",\r\n          \"url\": \"https:\/\/reqres.in\/api\/users?page=2\",\r\n          \"output\": {\r\n            \"user_names\": \"[.data[].first_name] | join(\\\", \\\")\"\r\n          }\r\n        }\r\n      ]\r\n    },\r\n    {\r\n      \"name\": \"publish_somewhere\",\r\n      \"steps\": [\r\n        {\r\n          \"name\": \"send_to_requestbin\",\r\n          \"type\": \"http\",\r\n          \"method\": \"post\",\r\n          \"url\": \"http:\/\/requestbin.fullcontact.com\/1lgnjpn1\",\r\n          \"body\": {\r\n            \"some_input\": \"{{input.value}}\",\r\n            \"names\": \"{{output.get_users.fetch_fake_api.user_names}}\"\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  ]\r\n}";
  const input = {value: 'hello'};
  await exec(definition, input);
});
